### ISSUE TITLE
Single-table deduplication issue

### ISSUE THREAD

**Issue by vromaniello** [chu-data-lab/zeroer#1]
Hi @wurenzhi ,

I am testing your tool with some trial datasets but with no success cause of an error occured during single-table deduplication process. 

Running the `python zeroer.py restaurant --LR_identical` command i get this error:

```
(ZeroER) C:\ER\zeroer-main>python zeroer.py restaurant --LR_identical
Generating features and storing in: datasets\restaurant/candset_features_df.csv
Metadata file is not present in the given path; proceeding to read the csv file.
Metadata file is not present in the given path; proceeding to read the csv file.
Traceback (most recent call last):
  File "zeroer.py", line 24, in <module>
    candset_features_df = pd.read_csv(join(dataset_path,"candset_features_df.csv"), index_col=0)
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\io\parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\io\parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\io\parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\io\parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\io\parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\restaurant\\candset_features_df.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zeroer.py", line 59, in <module>
    include_self_join=False)
  File "C:\ER\zeroer-main\data_loading_helper\data_loader.py", line 12, in load_data
    C = blocking_fn(A, B)
TypeError: 'str' object is not callable
```

I updated the _metadata.txt_ and added the .csv files into datasets folder  (e.g.  ..._\ER\zeroer-main\datasets\restaurant_).
I used two .csv files:

- _restaurant.csv_ (a list of data)
- _restaurant_gold.csv_ (Ground Truth matches)

1° attempt: original files .csv (different format than your examples) [test1.zip](https://github.com/chu-data-lab/zeroer/files/8838063/test1.zip)

2° attempt: files .csv with the same format of your examples [test2.zip](https://github.com/chu-data-lab/zeroer/files/8838064/test2.zip)

What am I doing wrong?

NB: Using the same command and the example datasets file (fodors_zagats_single) everything works fine!

Thank you very much for the support.

**Comment by wurenzhi** [comment]
Hi, you should create a blocking function for your dataset in `blocking_functions.py` and edit the dictionary `blocking_functions_mapping` in that file accordingly.

**Comment by vromaniello** [comment]
Thanks, is there any guide on how to create a blocking function?

**Comment by wurenzhi** [comment]
> Thanks, is there any guide on how to create a blocking function?

Please refer to other blocking functions in `blocking_functions.py`. For your example dataset, you can adapt the existing blocking function `block_fodors_zagats`. 
You can also check out the documentation of py_entitymatching (http://anhaidgroup.github.io/py_entitymatching/v0.3.3/user_manual/blocking.html) that we used in zeroer for blocking.

**Comment by vromaniello** [comment]
I tried with the following blocking function (I have just a single table dataset):

```
def block_vr_restaurants(A, B):
    ob = em.OverlapBlocker()
    C = ob.block_tables(A, B, 'name', 'name', l_output_attrs=['name', 'addr', 'city', 'phone', 'type', 'class'],  r_output_attrs=['name', 'addr', 'city', 'phone','type', 'class'],
        overlap_size=1, show_progress=False)
    return C
```

but I get this exception:


```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zeroer.py", line 67, in <module>
    candset_features_df = gather_features_and_labels(ltable_df, rtable_df, duplicates_df, candset_df)
  File "C:\ER\zeroer-main\data_loading_helper\feature_extraction.py", line 141, in gather_features_and_labels
    labels_df.columns = ["ltable_id", "rtable_id"]
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\core\generic.py", line 5154, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas\_libs\properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\core\generic.py", line 564, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "C:\Users\v.romaniello\Anaconda3\envs\ZeroER\lib\site-packages\pandas\core\internals\managers.py", line 227, in set_axis
    f"Length mismatch: Expected axis has {old_len} elements, new "
ValueError: Length mismatch: Expected axis has 3 elements, new values have 2 elements
```

Attached:
- Data rows [restaurants.csv](https://github.com/chu-data-lab/zeroer/files/8838214/restaurants.csv)
- Gold truth matches [restaurants_gold.csv](https://github.com/chu-data-lab/zeroer/files/8838213/restaurants_gold.csv)

Thanks

**Comment by wurenzhi** [comment]
hi, you should only have two columns (lid, rid) in your gold csv file. Please refer to https://github.com/chu-data-lab/zeroer/tree/main/datasets/fodors_zagats_single

**Comment by vromaniello** [comment]
Yes, the error was due to the third column in the gold file. 
Now the execution is successful.

Thank you very much for the support!
